---
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/github"
- - "@iwavesmedia/semantic-release-composer"
  - skipOnMissingComposerJson: true
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets: ["CHANGELOG.md", "composer.json"]
branches:
  - "main"