name: Release
on:
  push:
    branches:
      - main
      - release
    tags-ignore:
      - v*
    paths-ignore:
      - 'CHANGELOG.md'
permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/github @semantic-release/git @semantic-release/changelog
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
      - name: Rebase dev branch on master
        if: success()
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "your-email@example.com"
          git checkout main
          git pull
          git checkout dev
          git rebase main
          git push --force-with-lease origin dev
