name: Check composer.json Version Not Changed
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Version Key Update
        id: check_version_changes
        run: |
            changed_lines=$(git diff -r --unified=0 d07d0cea7b0affbf1fe2414c4fb06ddba3378548 607ca75885a04371b93c120feea8779d759fbb53 -- composer.json | grep -c "version")
            echo "$changed_lines"
            if [ "$changed_lines" -eq 0 ]; then
                echo "Error: version in composer.json should not be updated manually."
                exit 1
            fi
            exit 0


