name: Check composer.json Version Not Changed
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Version Key Update
        id: check_version_changes
        run: |
          changed_lines=$(git diff -r --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- composer.json | grep -c "version")
          if [ "$changed_lines" -ne "0" ]; then
            echo "Error: version in composer.json should not be updated manually."
            exit 1
          fi


